id: P44F49667
initial_creation_type: ocr
source_metadata:
  volumes:
    d91cee96fd5349fbb77c9cf7183b6fbe:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་མགོན་པོའི་གཏོར་མ།
      total_pages: 1856
      volume_number: 14
